// examples/lit/contacts/src/routes/handlers/index.ts
import type { RouteHandlers } from '@remix-run/fetch-router';
import { render } from '@webstd-ui/router';
import { CONTACTS_KEY, getContacts } from '~/lib/contacts.ts';
import type { routes } from '~/routes/index.ts';

import { create, destroy, favorite, update } from './actions.ts';
import { edit } from './edit-contact.ts';
import { show } from './show-contact.ts';
import { html } from 'lit';

export const handlers = {
    async index({ storage, url }) {
        const query = url.searchParams.get('q');
        const contacts = await getContacts(query);
        storage.set(CONTACTS_KEY, contacts);

        return render(html`
            <p id="index-page">
                This is a demo for
                <a href="https://www.npmjs.com/package/@webstd-ui/router" target="_blank">
                    <code>@webstd-ui/router</code>
                </a>
                + Lit.
                <br />
                Check out
                <a
                    href="https://github.com/webstd-ui/router/tree/main/examples/lit/contacts"
                    target="_blank"
                >
                    the code at github.com/webstd-ui/router</a
                >.
            </p>
        `);
    },
    contact: {
        // Pages
        show,
        edit,
        // Actions
        create,
        destroy,
        update,
        favorite,
    },
} satisfies RouteHandlers<typeof routes>;

// examples/tasks/src/handlers.tsx
import { type RouteHandlers, redirect } from "@remix-run/fetch-router";
import { delay as sleep } from "@std/async";
import { render } from "@webstd-ui/router";
import { NewTask } from "./components/NewTask.tsx";
import { addTask, deleteTask, getTasks } from "./lib/task-data.ts";
import { routes } from "./routes.ts";

export const handlers = {
    async index() {
        return redirect(routes.tasks.show.href({ id: 1 }));
    },
    tasks: {
        async show({ params }) {
            await sleep(800);
            const task = getTasks().find(t => t.id === params.id);

            return render(
                <>
                    <h3>Task</h3>
                    <p>{task?.name}</p>
                </>,
            );
        },
        async destroy({ params, formData }) {
            await sleep(800);
            deleteTask(params.id);

            const redirectId = formData.get("redirect-id") as string;
            return redirect(
                redirectId ? routes.tasks.show.href({ id: redirectId }) : routes.tasks.new.href(),
            );
        },
        async new() {
            return render(
                <>
                    <h3>New Task</h3>
                    <NewTask />
                </>,
            );
        },
        async create({ formData }) {
            await sleep(800);
            addTask(formData.get("new-task") as string);
            return redirect(routes.index.href(), { status: 302 });
        },
    },
} satisfies RouteHandlers<typeof routes>;
