// examples/remix/contacts/src/components/CancelButton.tsx
import type { Remix } from "@remix-run/dom";
import { dom } from "@remix-run/events";
import { App } from "~/app.tsx";

export function CancelButton(this: Remix.Handle) {
    const router = this.context.get(App);
    const goBack = dom.click(() => router.navigate(-1));

    return () => (
        <button on={goBack} type="button">
            Cancel
        </button>
    );
}

// examples/lit/contacts/src/custom-elements/cancel-button.ts
import { dom } from '@remix-run/events';
import { on } from '~/directives/on.ts';
import { html, LitElement } from 'lit';
import { formControlStyles } from '~/styles.ts';

export class CancelButton extends LitElement {
    static tag = 'app-cancel-button';

    static styles = [formControlStyles];

    private goBack = dom.click(() => history.back());

    public render() {
        return html`<button ${on(this.goBack)} type="button">Cancel</button>`;
    }
}
