// examples/lit/contacts/src/custom-elements/delete-button.ts
import { dom } from '@remix-run/events';
import { css, html, LitElement } from 'lit';
import { property } from 'lit/decorators.js';
import { on } from '~/directives/on.ts';
import { restful } from '~/directives/restful-form.ts';
import { RouterConsumer } from '~/base-classes/router-consumer.ts';
import { routes } from '~/routes/index.ts';
import { formControlStyles } from '~/styles.ts';

export class DeleteButton extends RouterConsumer(LitElement) {
    static tag = 'app-delete-button';

    static styles = [
        formControlStyles,
        css`
            button {
                color: #f44250;
            }
        `,
    ];

    @property({ attribute: false })
    public accessor contactId!: string;

    private confirm = dom.submit(event => {
        if (!confirm('Please confirm you want to delete this record.')) {
            event.preventDefault();
        }
    });

    public render() {
        return html`
            <form
                action=${routes.contact.destroy.href({ contactId: this.contactId })}
                ${restful({ method: 'delete' })}
                ${on([this.confirm, this.router.submitHandler])}
            >
                <button type="submit">Delete</button>
            </form>
        `;
    }
}

// examples/crank/contacts/src/components/DeleteButton.tsx
import type { Context } from "@b9g/crank";
import { routes } from "~/routes/mod";
import { RestfulForm } from "./RestfulForm.tsx";

export function* DeleteButton(this: Context<{ id: string }>, _props: { id: string }) {
    for (const { id } of this) {
        yield (
            <RestfulForm
                action={routes.contact.destroy.href({ contactId: id })}
                data-destroy
                method="DELETE"
                onsubmit={(event: Event) => {
                    if (!confirm("Please confirm you want to delete this record.")) {
                        event.preventDefault();
                    }
                }}
            >
                <button type="submit">Delete</button>
            </RestfulForm>
        );
    }
}
